name: RanchoRPG
main: dev.rancho.RanchoPlugin
version: ${project.version}
api-version: '1.21'
author: Kurjr
description: Sistema RPG profundo de ganadería, cultivo, clima y estaciones.
softdepend: [Vault, PlaceholderAPI]

commands:
  rancho:
    description: Menú principal de RanchoRPG
    usage: /rancho [admin|info|temp|libreta|termometro|give|spawn|npc|reload]
    aliases: [ranch]

permissions:
  rancho.use:
    description: Usar /rancho, el menú principal, la libreta, el mercado y las habilidades
    default: true
  rancho.admin:
    description: Panel /rancho admin, /rancho reload, give, spawn y npc
    default: op
  rancho.*:
    description: Todos los permisos de RanchoRPG
    default: op
    children:
      rancho.use: true
      rancho.admin: true
